# Generated by Django 2.2.6 on 2019-10-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('Steps', 'Date')},
        ),
    ]
